
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SYSCOM
 */
public class about extends javax.swing.JFrame {

    /**
     * Creates new form about
     */
    public about() {
        initComponents();
        
         ImageIcon icon =new ImageIcon(getClass().getResource("/image/c.png"));
 Image img=icon.getImage();
  Image imgscale=img.getScaledInstance(label2.getWidth(),label2.getHeight(),Image.SCALE_SMOOTH);
ImageIcon  scaledicon=new ImageIcon(imgscale);
label2.setIcon(scaledicon);


icon =new ImageIcon(getClass().getResource("/image/b.png"));
  img=icon.getImage();
  imgscale=img.getScaledInstance(label1.getWidth(),label1.getHeight(),Image.SCALE_SMOOTH);
 scaledicon=new ImageIcon(imgscale);
label1.setIcon(scaledicon);



icon =new ImageIcon(getClass().getResource("/image/back.png"));
  img=icon.getImage();
  imgscale=img.getScaledInstance(30,40,Image.SCALE_SMOOTH);
 scaledicon=new ImageIcon(imgscale);
jButton1.setIcon(scaledicon);


icon =new ImageIcon(getClass().getResource("/image/d.png"));
  img=icon.getImage();
  imgscale=img.getScaledInstance(label3.getWidth(),label3.getHeight(),Image.SCALE_SMOOTH);
 scaledicon=new ImageIcon(imgscale);
label3.setIcon(scaledicon);
/*
icon =new ImageIcon(getClass().getResource("/image/4.png"));
  img=icon.getImage();
  imgscale=img.getScaledInstance(label3.getWidth(),label3.getHeight(),Image.SCALE_SMOOTH);
 scaledicon=new ImageIcon(imgscale);
label3.setIcon(scaledicon);


icon =new ImageIcon(getClass().getResource("/image/3.png"));
  img=icon.getImage();
  imgscale=img.getScaledInstance(label4.getWidth(),label4.getHeight(),Image.SCALE_SMOOTH);
 scaledicon=new ImageIcon(imgscale);
label4.setIcon(scaledicon);*/


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        label3 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("The largest fitness club in Nablus\n designed with the latest modern designs\n The club consists of two separate halls for men and women\n equipped with all the advanced and modern sports equipment necessary \nto build a perfect body with the help of the most skilled trainers \nwho have local and international certificates and championships\nAnd it was equipped with accurate and modern safety devices \nto feel comfortable when exercising The club provides all necessary\n services to subscribers as it has a cafeteria and a special section \nfor selling proteins.\n");
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 116, 831, 270));

        label3.setText("jLabel1");
        jPanel2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 393, 416, 360));

        label1.setText("jLabel1");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 393, 416, 350));

        label2.setText("jLabel1");
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 393, 416, 360));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("About us");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 370, 70));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);
        new home().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new about().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    // End of variables declaration//GEN-END:variables
}
